import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import { data, IData } from '../mock/data';
import { SpeechButton } from '../components/SpeechButton';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const play = (filename: string) => {
    let sound = document.getElementById(filename) as HTMLAudioElement;
    sound.pause();
    sound.currentTime = 0;
    sound.play();
  };
  useEffect(() => {
    document.getElementById('body')?.addEventListener('keypress', (e) => {
      if (e.key === '1') {
        play('ora');
      } else if (e.key === '2') {
        play('the-world');
      } else if (e.key === '3') {
        play('giorno');
      }
    });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="body" className={styles.main}>
        <div
          tabIndex={0}
          onKeyDown={(e) => {
            console.info(e.key);
          }}
        >
          {data.map((data: IData) => (
            <SpeechButton
              key={data.filename}
              label={data.label}
              filename={data.filename}
            />
          ))}
        </div>
      </main>
    </>
  );
}
